# Generated by Django 2.1 on 2018-08-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=128, verbose_name='surname')),
                ('about_desc', models.TextField(blank=True, verbose_name='about_desc')),
                ('birthday', models.DateField(blank=True, verbose_name='birthday')),
                ('location', models.CharField(blank=True, max_length=128, verbose_name='location')),
                ('email', models.CharField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=256, verbose_name='organization')),
                ('region', models.CharField(max_length=128, verbose_name='region')),
                ('site', models.URLField(verbose_name='site')),
                ('position', models.CharField(max_length=256, verbose_name='position')),
                ('official_duties', models.TextField(verbose_name='official_duties')),
                ('start_time', models.DateField(blank=True, verbose_name='start_time')),
                ('end_time', models.DateField(blank=True, verbose_name='end_time')),
            ],
        ),
    ]
