# Generated by Django 2.1 on 2018-08-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=128, verbose_name='surname')),
                ('about_desc', models.TextField(blank=True, verbose_name='about_desc')),
                ('birthday', models.DateField(blank=True, verbose_name='birthday')),
            ],
        ),
    ]
