# Generated by Django 2.1 on 2018-08-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=256, verbose_name='organization')),
                ('region', models.CharField(max_length=128, verbose_name='region')),
                ('site', models.URLField(verbose_name='site')),
                ('position', models.CharField(max_length=256, verbose_name='position')),
                ('official_duties', models.TextField(verbose_name='official_duties')),
                ('start_time', models.DateField(verbose_name='start_time')),
            ],
        ),
    ]
