# Generated by Django 2.1 on 2018-08-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='end_time'),
        ),
    ]
