# Generated by Django 2.1 on 2018-08-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180831_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('speciality', models.CharField(max_length=128, verbose_name='speciality')),
                ('description', models.TextField(verbose_name='description')),
                ('end_date', models.DateField(verbose_name='end_date')),
            ],
        ),
    ]
