# Generated by Django 2.1.1 on 2018-09-05 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180831_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('site', models.URLField(verbose_name='site')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('address', models.TextField(verbose_name='address')),
                ('local_url', models.URLField(verbose_name='local_url')),
                ('phone', models.CharField(max_length=32, verbose_name='phone')),
                ('desc', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='site',
        ),
        migrations.AlterField(
            model_name='work',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Organization', verbose_name='organization'),
        ),
    ]
