# Generated by Django 2.1.1 on 2018-09-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20180905_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='organization',
            new_name='org_id',
        ),
    ]
