# Generated by Django 2.1.1 on 2018-09-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20180905_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='org_id',
            new_name='organization',
        ),
    ]
