# Generated by Django 2.1 on 2018-09-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20180905_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='yandex_map',
            field=models.TextField(blank=True, null=True, verbose_name='yandex_map'),
        ),
    ]
